# .platform.app.yaml

name: app

type: php:8.2

runtime:
  extensions:
    - curl
    - pdo_mysql
    - imagick
disk: 128
mounts:
  "/app/img": "shared:files/img"
  "/app/data.json": "shared:files/data.json"
