# .platform.app.yaml

name: app

type: php:8.2

runtime:
  extensions:
    - curl
    - pdo_mysql
    - imagick

web:
  locations:
    "/":
      root: "dist"
      allow: true
      passthru: "/index.html"
      expires: -1
      scripts: true
      index: ["index.html"]

disk: 128
